### ISSUE TITLE
Wrong in the function "int32_t lsm6ds3_fifo_watermark_set(stmdev_ctx_t *ctx, uint16_t val)"

### ISSUE THREAD

**Issue by Jiabin-develop** [STMicroelectronics/lsm6ds3-pid#1]
Hi,

  I found that there is a mistake in the following function 
        int32_t lsm6ds3_fifo_watermark_set(stmdev_ctx_t *ctx, uint16_t val)
  The following code is wrong:
        fifo_ctrl1.fth = (uint8_t)(val & 0x00FF0U);
  It should be as following:
        fifo_ctrl1.fth = (uint8_t)(val & 0x00FFU);

  Hope it can be helpful.

**Comment by avisconti** [comment]
Fixed by 9ba38a873d4d8af0e0fc19a8387ef28f3b1425bd
